name: Deploy

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm ci --legacy-peer-deps
      - run: git config user.email "psamim@gmail.com"
      - run: git config user.name "Samim Pezeshki"
      - run: npm run deploy
        env:
          GITHUB_TOKEN: ${{secrets.TOKEN}}
